# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_profile_registered_workshops'),
        ('event', '0002_auto_20161218_0603'),
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('days', models.IntegerField(default=0)),
                ('invoice_type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.IntegerField(max_length=5)),
                ('pending', models.BooleanField(default=True)),
                ('success', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('post_data', models.TextField()),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workshop.Workshop')),
            ],
        ),
    ]
