# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('data', models.TextField()),
            ],
            options={
                'ordering': ['-date'],
                'verbose_name_plural': 'Analytics',
            },
        ),
    ]
