# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.IntegerField(blank=True, help_text=b'2 or 3 or 4', max_length=2, null=True),
        ),
    ]
