# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-25 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20161218_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=100, max_length=5),
        ),
    ]
