# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-views'], 'permissions': (('change_own', 'Change events incharge of'), ('see_events', 'See all events'))},
        ),
    ]
