# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20170128_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, choices=[(b'cse', b'Computer Science'), (b'ec', b'Electronics'), (b'mech', b'Mechanical'), (b'civil', b'Civil')], default=b'cse', max_length=20, null=True),
        ),
    ]
