# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170205_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price_1',
            field=models.IntegerField(default=50, help_text=b'Numeric, Eg: 5000'),
        ),
        migrations.AddField(
            model_name='event',
            name='price_2',
            field=models.IntegerField(default=50, help_text=b'Numeric, Eg: 5000'),
        ),
        migrations.AddField(
            model_name='event',
            name='price_3',
            field=models.IntegerField(default=50, help_text=b'Numeric, Eg: 5000'),
        ),
    ]
