# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-06 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20170206_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='price_1',
            new_name='prize_1',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='price_2',
            new_name='prize_2',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='price_3',
            new_name='prize_3',
        ),
    ]
