# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20161205_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Profile')),
            ],
            options={
                'ordering': ['-created'],
                'permissions': (('own_rightclick_registrations', 'View registrations for admin'),),
            },
        ),
        migrations.AlterUniqueTogether(
            name='registrationrc',
            unique_together=set([('profile',)]),
        ),
    ]
