# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='events',
            field=models.ManyToManyField(blank=True, help_text='The event this profile is in-charge of', null=True, related_name='heads', to='event.Event', verbose_name='Events Incharge of'),
        ),
        migrations.AddField(
            model_name='profile',
            name='hospitality_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='registered_events',
            field=models.ManyToManyField(through='event.Registration', to='event.Event'),
        ),
    ]
