# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
        ('main', '0002_auto_20161205_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registered_workshops',
            field=models.ManyToManyField(blank=True, null=True, to='workshop.Workshop'),
        ),
    ]
