# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_auto_20161205_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('header_text', models.CharField(blank=True, default=b'', max_length=100)),
                ('img1_desc', models.CharField(blank=True, default=b'', max_length=100)),
                ('img2_desc', models.CharField(blank=True, default=b'', max_length=100)),
                ('img1', models.URLField(help_text=b'Imgur direct JPG url, 250x250 px')),
                ('img2', models.URLField(help_text=b'Imgur direct JPG url, 250x250 px')),
                ('answer', models.CharField(help_text=b'Answer is case insensitive', max_length=50)),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='QuestScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_level', models.IntegerField(default=1)),
                ('max_time', models.DateTimeField()),
                ('sort_key', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quest_score', to='main.Profile')),
            ],
            options={
                'ordering': ['-sort_key'],
            },
        ),
    ]
