# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, default=b'', max_length=50, null=True)),
                ('private_slug', models.CharField(blank=True, default=b'', max_length=50, null=True)),
                ('registrations_open', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50)),
                ('desc_1', models.TextField()),
                ('desc_2', models.TextField()),
                ('std_1_name', models.CharField(max_length=50)),
                ('std_1_mobile', models.CharField(max_length=10)),
                ('std_2_name', models.CharField(max_length=50)),
                ('std_2_mobile', models.CharField(max_length=10)),
                ('faculty_name', models.CharField(max_length=50)),
                ('faculty_mobile', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=5)),
                ('date_string', models.CharField(blank=True, help_text=b'Eg: From 20th to 21st of February', max_length=50, null=True)),
                ('img_big', models.URLField(help_text=b'400x400')),
                ('img_small', models.URLField(help_text=b'120x120')),
            ],
        ),
    ]
