# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_workshop_w_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='w_type',
            field=models.CharField(choices=[(b'Technical', b'Technical'), (b'Non-Technical', b'Non-Technical')], default=b'Technical', max_length=20),
        ),
    ]
