# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_auto_20170126_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='faculty_mobile',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='std_2_mobile',
        ),
        migrations.RemoveField(
            model_name='workshop',
            name='std_2_name',
        ),
        migrations.AddField(
            model_name='workshop',
            name='faculty_email',
            field=models.EmailField(default=b'dggs222@gmail.com', max_length=254, verbose_name=b'Email Address'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='std_1_email',
            field=models.EmailField(default=b'dggs222@gmail.com', max_length=254, verbose_name=b'Email Address'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='venue',
            field=models.CharField(blank=True, help_text=b'Eg: Block:C, 205 Room', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='date_string',
            field=models.CharField(blank=True, help_text=b'Eg: From 2, 3 or 4 March', max_length=50, null=True),
        ),
    ]
