# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-30 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_auto_20170130_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='max_range',
            field=models.IntegerField(default=40, max_length=2),
        ),
    ]
