# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0005_workshop_max_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='min_range',
            field=models.IntegerField(default=0, max_length=2),
        ),
    ]
